name = "HAdaptiveIntegration"
uuid = "eaa5ad34-b243-48e9-b09c-54bc0655cecf"
version = "1.0.0"
authors = ["Zois Moitier", "Luiz M. Faria"]

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

[extensions]
IncreasePrecisionExt = "ForwardDiff"

[compat]
Aqua = "0.8"
DataStructures = "0.18, 0.19"
ForwardDiff = "1"
LinearAlgebra = "1"
Logging = "1"
Printf = "1"
Quadmath = "0.5"
StaticArrays = "1"
Test = "1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "DataStructures", "Quadmath", "LinearAlgebra", "Logging", "Test"]
