[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HAdaptiveIntegration = "eaa5ad34-b243-48e9-b09c-54bc0655cecf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
