[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
HAdaptiveIntegration = "eaa5ad34-b243-48e9-b09c-54bc0655cecf"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[sources]
HAdaptiveIntegration = {path = "../HAdaptiveIntegration.jl"}
